require 'view_mapper/auto_complete_view'
require 'view_mapper/paperclip_view'
require 'view_mapper/has_many_view'
require 'view_mapper/route_action'
require 'view_mapper/editable_manifest'
require 'view_mapper/model_info'
require 'view_mapper/view_mapper'
